### ISSUE TITLE
The reason prefer llvm 4.01 rather than 5.0.

### ISSUE THREAD

**Issue by nbsn2** [NETMF/Llvm.NET#15]
Sure we know llvm 5.0 is in rc+ status, but not so far for a final release.
Will llvm.net branch 4.01 be easily transfered to adapt  llvm 5.0, or else if there is huge obstacle to resolve so make branch 4.01 more important?

**Comment by smaillet** [comment]
the 4.01 branch is actually based on the 5.0 branch, though it has undergone a number of changes to finish up the attributes support. The remaining differences should be fairly straight forward to move to v5.0 once it reaches a final release. The bulk of the effort at this point is on getting Full AppVeyor builds and NUGET packages built and published. So that as soon as 5.0 is ready there will be a functional automated/repeatable build process in place. This sets things up for greater open collaboration.
