### ISSUE TITLE
Update to 3.80 RTM

### ISSUE THREAD

**Issue by smaillet-ms** [NETMF/Llvm.NET#4]
Currently only tested and supported on RC1 (Don't expect any issues but need to rebuild the libs and test)

**Comment by jschroedl** [comment]
I just tried building against 3.8 RTM and hit a number of errors. Here's the first (Using VS 2015 Update 1) -- would love to be able to try llvm.net but can't.

d:\llvm.net\src\libllvm\valuebindings.h(12): error C2371: 'LLVMValueKind': redefinition; different basic types [D:\Llvm.NET\src\LibLLVM\LibLLVM.vcxproj]
d:\llvm\include\llvm-c\core.h(280): note: see declaration of 'LLVMValueKind'

**Comment by smaillet-ms** [comment]
Investigating, thanks for the info.

**Comment by smaillet-ms** [comment]
Can you provide the exact steps from a clean install you are using when you get this? I've installed to official RTM release LLVM source, built it using the provided build script, and built the LLVM.NET code using the generated libs and headers without seeing that error.

**Comment by jschroedl** [comment]
* git clone llvm.net into d:\llvm.net\
* Failed attempt to d/l llvm from the link in README.MD
http://llvm.org/pre-releases/3.8.0/rc2/llvm-3.8.0rc2.src.tar.xz is not extractable on my system using WinZip (also tried tar -xf which rejects the file)
This led me to try RTM...
* git cloned llvm 3.8 RTM from llvm repo into d:\llvm\ instead.  
https://github.com/llvm-mirror/llvm
* Copied BuildLlvmWithVS.cmd into d:\llvm\
* Ran BuildLlvmWithVS.cmd 
* Failed build due to missing python
* Installed python 3.5.2 for Windows x64
* Ran BuildLlvmWithVS.cmd 
* Failed build due to missing cmake
* Installed cmake 3.6.0-rc3
* Ran BuildLlvmWithVS.cmd  -- build ran over night and seems to have succeeded. 
Note during build that it shows Clang is version 3.9.0 though I don't know if that's tied to LLVM version #.
* Opened d:\llvm.net\src\llvm.net.sln
* Set llvm.net as Startup Project. Build Debug Win32.  Hit errors mentioned.
* Exited and tried msbuild BuildAll.slnproj  Hit same errors.

Double-checked regkey:
HKEY_LOCAL_MACHINE\SOFTWARE\LLVM\3.8.0   
SrcRoot value is "D:\llvm\"  which looks correct so it does seem to reference the proper include dirs.

Any other info needed?

Here's the file in github with the enum it's citing which is redefined by ValueBindings.h.
[https://github.com/llvm-mirror/llvm/blob/master/include/llvm-c/Core.h#L280]

**Comment by jschroedl** [comment]
I am re-downloading the official llvm src. Clearly the git clone is not updated every 5 minutes as it claims.

I'd never heard of xz until today and the official download is named with that extension but it does seem to be a xz file and my extraction worked this time!

Looking at Core.h now, I don't see the conflict so I suspect all will be well with my build tonight.

**Comment by smaillet-ms** [comment]
Ah, steps 2&3 are what did it. The GitHub mirror reflects the current head of the development branch for the next version(e.g. 3.9) and NOT the stable released one (3.8.0). 

I've updated the readme to  point to the current source archive. 

At least this is a heads up on 3.9.0, which is expected to Release end of Aug. so there's a little time to deal with any changes.

Thanks for the feedback!

**Comment by jschroedl** [comment]
My build finished and LLVM.NET builds as well. huzzah! Now to kick the tires. Sorry for the noise.

**Comment by smaillet-ms** [comment]
Nice, no problem at all, it was a "bug" in the readme docs - which has been updated, and a heads up on some changes in 3.9 so all good in the end.
